# Generated by Django 5.1 on 2024-10-21 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotasENEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linguagens_nota', models.FloatField(blank=True, null=True)),
                ('linguagens_peso', models.FloatField(blank=True, null=True)),
                ('matematica_nota', models.FloatField(blank=True, null=True)),
                ('matematica_peso', models.FloatField(blank=True, null=True)),
                ('natureza_nota', models.FloatField(blank=True, null=True)),
                ('natureza_peso', models.FloatField(blank=True, null=True)),
                ('humanas_nota', models.FloatField(blank=True, null=True)),
                ('humanas_peso', models.FloatField(blank=True, null=True)),
                ('redacao_nota', models.FloatField(blank=True, null=True)),
                ('redacao_peso', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
