# Generated by Django 5.1 on 2024-10-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('linguagens_peso', models.FloatField(default=1.0)),
                ('matematica_peso', models.FloatField(default=1.0)),
                ('natureza_peso', models.FloatField(default=1.0)),
                ('humanas_peso', models.FloatField(default=1.0)),
                ('redacao_peso', models.FloatField(default=1.0)),
            ],
        ),
    ]
