# Generated by Django 5.1 on 2024-10-21 19:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_curso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notasenem',
            name='humanas_peso',
        ),
        migrations.RemoveField(
            model_name='notasenem',
            name='linguagens_peso',
        ),
        migrations.RemoveField(
            model_name='notasenem',
            name='matematica_peso',
        ),
        migrations.RemoveField(
            model_name='notasenem',
            name='natureza_peso',
        ),
        migrations.RemoveField(
            model_name='notasenem',
            name='redacao_peso',
        ),
        migrations.AddField(
            model_name='notasenem',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.curso'),
        ),
        migrations.AddField(
            model_name='notasenem',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notasenem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
